### ISSUE TITLE
Wine from Welcome Screen

### ISSUE THREAD

**Issue by javieryo** [feren-OS/Feren-OS-Dependency-Issue-Reporting#1] opened 2019-04-23 09:05 UTC
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: wine-duo-feren

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```
(javieryo didn't fill this part in)
```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by feren** [comment] 2019-04-24 20:02
@javieryo Try this fix:
`sudo apt install --reinstall libqt5core5a -y`

**Comment by feren** [comment] 2019-04-24 20:05
If this fixes the issue, be sure to close this issue or let me know.

**Comment by dominichayesferen** [comment] 2019-04-24 20:06
Thanks for reporting this issue, I'll check in a new Feren OS install to see what the issue is. Alternatively, you can update your comment to include the output of `sudo apt-get install wine-duo-feren`.

**Comment by dominichayesferen** [comment] 2019-04-24 20:13
Alright, the issue has been reproduced, I'll look into it.

**Comment by dominichayesferen** [comment] 2019-04-24 20:24
@javieryo Alright, I've found a fix (it'll be implemented in an ISO Update that'll hopefully happen tomorrow):
**Downgrade 'libblkid1' via Software Sources > Maintenance > Downgrade Foreign Packages**

It appears that for the time that libblkid1 from KDE Neon was in my mirror of the KDE Neon Repositories before I then removed it for its dependency issues with Wine, Feren OS ISOs ended up getting that now deleted version of that package. Since it has been deleted from my repository, it's now a 'foreign' package with an 'older' version on the Ubuntu Package Repositories. Therefore, by going into Software Sources > Maintenance > Downgrade Foreign Packages to downgrade it you can then install 'wine-duo-feren' successfully following that package being downgraded to the version present on the Ubuntu Package Repositories.

**Comment by dominichayesferen** [comment] 2019-04-25 20:34
Alright, this has now been fixed in the latest update for the Feren OS 64-Bit ISO, thanks for reporting this issue.

**Closed as completed** 2019-04-25 20:34 UTC
Labels: Fixed, Confirmed
